name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify Python
        run: |
          python3 --version
          which python3

      - name: Create backend directory
        run: |
          sudo mkdir -p /opt/backend
          sudo chown -R ubuntu:ubuntu /opt/backend

      - name: Deploy backend code
        run: |
          rsync -av --delete aws/backend/ /opt/backend/

      - name: Create virtual environment & install deps
        run: |
          cd /opt/backend

          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi

          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restart backend
        run: |
          sudo pkill -f app.py || true
          cd /opt/backend
          source venv/bin/activate
          nohup python app.py > app.log 2>&1 &
